name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v6

      - name: Verificar README
        run: test -f README.md

      - name: Verificar segredos
        uses: gitleaks/gitleaks-action@v3
